name: CI Build and Docker Push

on:
  push:
    branches:
      - main
      - develop
      - feature/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using GitHub Secrets
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.REGiSTRY_USERNAME }}" --password-stdin

      # Step 3: Set image tags
      - name: Set image tags
        id: vars
        run: |
          BRANCH_TAG=$(echo "${GITHUB_REF##*/}" | tr / -)
          COMMIT_TAG=${GITHUB_SHA::7}
          echo "BRANCH_TAG=$BRANCH_TAG" >> $GITHUB_ENV
          echo "COMMIT_TAG=$COMMIT_TAG" >> $GITHUB_ENV

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.REGISTRY_USERNAME }}/your-image-name:latest \
                          -t ${{ secrets.REGISTRY_USERNAME }}/your-image-name:${{ env.BRANCH_TAG }} \
                          -t ${{ secrets.REGISTRY_USERNAME }}/your-image-name:${{ env.COMMIT_TAG }} .

      # Step 5: Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.REGISTRY_USERNAME }}/your-image-name:latest
          docker push ${{ secrets.REGISTRY_USERNAME }}/your-image-name:${{ env.BRANCH_TAG }}
          docker push ${{ secrets.REGISTRY_USERNAME }}/your-image-name:${{ env.COMMIT_TAG }}
